apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: "/"
  labels:
    app: linkerd
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.linkerd.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: linkerd
spec:
  rules:
  {{- range .Values.linkerd.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: linkerd
              servicePort: 80
  {{- end -}}
 

