apiVersion: v1
kind: Service
metadata:
  name: linkerd
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
    prometheus.io/probe: {{ .Values.prometheus.probe | quote }}
    prometheus.io/path: {{ .Values.prometheus.path | quote }}
    prometheus.io/port: "80"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: outgoing
    port: 4140
  - name: incoming
    port: 4141
  - name: admin
    port: 80
  selector:
    app: linkerd
